MyDjango/MyDjango/urls.py
#coding:utf-8
"""test_project URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import *
from django.contrib import admin
from django.contrib.staticfiles import views as static_views
from learn import views
from django.conf import settings


urlpatterns = patterns('',
    # url(r'^home/$', views.index, name='home'),
    # url(r'^login/$', views.login, name='login'),
    # url(r'^user_login/', views.user_login, name='user_login'),
    # url(r'^logout/', views.logout, name='logout'),
    # url(r'^project/get_chip_name/', views.get_chip_name, name='get_chip_name'),
    # url(r'^projects/status', views.cmcc_project_gethome_project_info, name='cmcc_project_gethome_project_info'),
    # url(r'^projects/all', views.getproject_basic_info_by_all, name='getproject_basic_info_by_all'),
    # # url(r'^accounts/', include('users.urls')),
    # url(r'^add/(\d+)/(\d+)/$', views.old_add2_redirect), # 注意修改了这一行
    # url(r'^new_add/(\d+)/(\d+)/$', views.add2, name='add2'),
    # url(r'^admin/', include(admin.site.urls)),
    
    url(r'^$', views.index, name='index'),
    
#    url(r'^login/$', views.login, name='login'),
    url(r'^user_login/', views.user_login, name='user_login'),
    # url(r'^logout/', views.Logout, name='logout'),
#    url(r'^project/get_chip_name/', views.get_chip_name, name='get_chip_name'),
#     url(r'^enterHouse/', views.enterWareHouse, name='enterWareHouse'),
#     url(r'^issues/', views.issues, name='issues'),

    # url(r'^project/get_project_basic_question/(.+)/', views.get_project_basic_question, name='get_project_basic_question'),
    url(r'^project/get_project_name/(.+)/', views.get_project_name, name='get_project_name'),
    # url(r'^projects/status', views.cmcc_project_gethome_project_info, name='cmcc_project_gethome_project_info'),
    # url(r'^projects/all', views.getproject_basic_info_by_all, name='getproject_basic_info_by_all'),
    # url(r'^accounts/', include('users.urls')),
    # url(r'^add/(\d+)/(\d+)/$', views.old_add2_redirect), # 注意修改了这一行
    # url(r'^new_add/(\d+)/(\d+)/$', views.add2, name='add2'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^login/', include('login.urls', namespace="login")),
    url(r'^project/', include('project.urls', namespace='project')),
    url(r'', include('webuser.urls')),
    url(r'', include('movie.urls')),
    url(r'', include('project.urls')),
    url(r'', include('library.urls')),
    url(r'', include('community.urls')),

)

if settings.DEBUG:
    urlpatterns += [
        # url(r'^static/(?P<path>.*)$', static_views.static.serve, {'document_root': settings.STATIC_ROOT}, name="static"),
        url(r'^uploads/(?P<path>.*)$', static_views.static.serve, {'document_root': settings.MEDIA_ROOT}, name="uploads")
    ]

MyDjango/library/urls.py
from django.conf.urls import *
# from project import views
from login.models import User
from django.views.generic import DetailView, ListView

urlpatterns = patterns('',

#        url(r'^$', 'login.views.Login', name='Login'),
        url(r'^library', 'library.views.library', name='homepage'),
        url(r'^add_book', 'library.views.add_book', name='add_book'),
        url(r'^add_img', 'library.views.add_img', name='add_img'),
        url(r'^view_book_list', 'library.views.view_book_list', name='view_book_list'),
        url(r'^signup', 'library.views.signup', name='signup'),
        url(r'^login', 'library.views.login', name='login'),
        url(r'^set_password', 'library.views.set_password', name='set_password'),
        url(r'^logout', 'library.views.logout', name='logout'),
        url(r'^bookdetail/', 'library.views.bookdetail', name='bookdetail'),
        )

MyDjango/login/urls.py
from django.conf.urls import *
from login import views
from login.models import User
from django.views.generic import DetailView, ListView

urlpatterns = patterns('',
         
        url(r'^$', 'login.views.Login', name='Login'),
        url(r'^index/$', 'login.views.index', name = 'index'),
         
        )

MyDjango/library/models.py
from django.db import models
from django.contrib.auth.models import User

class MyUser(models.Model):
    user = models.OneToOneField(User)
    nickname = models.CharField(max_length=16)
    permission = models.IntegerField(default=1)

    def __unicode__(self):
        return self.user.username

class Book(models.Model):
    name = models.CharField(max_length=128)
    price = models.FloatField()
    author = models.CharField(max_length=128)
    publish_date = models.DateField()
    category = models.CharField(max_length=128)

    class META:
        ordering = ['name']

    def __unicode__(self):
        return self.name

class Image(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField()
    img = models.ImageField(upload_to='image/%Y/%m/%d/')
    book = models.ForeignKey(Book)

# Create your models here.

MyDjango/login/models.py
from django.db import models
from django.contrib import admin

class User(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    

# Create your models here.

MyDjango/library/views.py
#coding:utf-8
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import user_passes_test, login_required
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib import auth
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import MyUser, Book, Image
import logging
logger = logging.getLogger("django") # 为loggers中定义的名称


def library(request):
    active_menu = 'homepage'
    print request.user.is_authenticated()
    user = request.user if request.user.is_authenticated() else None
    print dir(user)
    # content = {
    #     'active_menu': homepage,
    #     'user': user,
    # }

    return render(request, 'library/index.html', locals())

@login_required
def add_book(request):
    logger.info("add_book...")
    active_menu = 'add_book'
    user = request.user
    state = None
    if request.method == 'POST':
        new_book = Book(
                name=request.POST.get('name', ''),
                author=request.POST.get('author', ''),
                category=request.POST.get('category', ''),
                price=request.POST.get('price', 0),
                publish_date=request.POST.get('publish_date', '')
        )
        new_book.save()
        state = 'success'
    logger.info(locals())
    # content = {
    #     'user': user,
    #     'active_menu': 'add_book',
    #     'state': state,
    # }
    return render(request, 'library/add_book.html', locals())

def add_img(request):
    user = request.user
    state = None
    active_menu = 'add_img'
    if request.method == 'POST':
        try:
            new_img = Image(
                    name=request.POST.get('name', ''),
                    description=request.POST.get('description', ''),
                    img=request.FILES.get('img', ''),
                    book=Book.objects.get(pk=request.POST.get('book', ''))
            )
            new_img.save()
        except Book.DoesNotExist as e:
            state = 'error'
            print(e)
        else:
            state = 'success'
    book_list = Book.objects.all()

    return render(request, 'library/add_img.html', locals())

def view_book_list(request):
    print 'view_book_list'
    active_menu = 'view_book'
    category_list = Book.objects.values_list('category', flat=True).distinct()
    print category_list
    query_category = request.GET.get('category', 'all')
    if not query_category or Book.objects.filter(category=query_category).count() is 0:
        query_category = 'all'
        book_list = Book.objects.all()
    else:
        book_list = Book.objects.filter(category=query_category)

    if request.method == 'POST':
        keyword = request.POST.get('keyword', '')
        book_list = Book.objects.filter(name__contains=keyword)
        query_category = 'all'

    paginator = Paginator(book_list, 5)
    page = request.GET.get('page')
    try:
        book_list = paginator.page(page)
    except PageNotAnInteger:
        book_list = paginator.page(1)
    except EmptyPage:
        book_list = paginator.page(paginator.num_pages)
    return render(request, 'library/view_book_list.html', locals())

def signup(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('homepage'))
    state = None
    if request.method == 'POST':
        password = request.POST.get('password', '')
        repeat_password = request.POST.get('repeat_password', '')
        if password == '' or repeat_password == '':
            state = 'password is not empty'
        elif password != repeat_password:
            state = 'password repeat_error'
        else:
            username = request.POST.get('username', '')
            if User.objects.filter(username=username):
                state = 'user_exist'
            else:
                new_user = User.objects.create_user(username=username, password=password,
                                                    email=request.POST.get('email', ''))
                new_user.save()
                new_my_user = MyUser(user=new_user, nickname=request.POST.get('nickname', ''))
                new_my_user.save()
                state = 'success'
    # content = {
    #     'active_menu': 'homepage',
    #     'state': state,
    #     'user': None,
    # }
    return render(request, 'library/singup.html', locals())




def login(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('homepage'))
    state = None
    if request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('homepage'))
        else:
            state = 'not_exist_or_password_error'
    # content = {
    #     'active_menu': 'homepage',
    #     'state': state,
    #     'user': None,
    # }
    return render(request, 'library/login.html', locals())

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('homepage'))

def set_password(request):
    user = request.user
    state = None
    active_menu = 'homepage'
    if request.method == 'POST':
        old_password = request.POST.get('old_password', '')
        new_password = request.POST.get('new_password', '')
        repeat_password = request.POST.get('repeat_password', '')
        if user.check_password(old_password):
            if not new_password:
                state = 'empty'
            elif new_password != repeat_password:
                state = 'repeat_error'
            else:
                user.set_password(new_password)
                user.save()
                state = 'success'
        else:
            state = 'password_error'

    return render(request, 'library/set_password.html', locals())

def bookdetail(request):
    user = request.user if request.user.is_authenticated() else None
    bookid = request.GET.get('id', '')

    book = Book.objects.get(pk=bookid)
    print book.image_set.all()
    for img in book.image_set.all():
        print img.img

    return render(request, 'library/detail.html', locals())
# Create your views here.

MyDjango/login/views.py
#coding=utf-8
from django.shortcuts import render, render_to_response, redirect
from django.http import HttpResponseRedirect
from login.models import User
from django import forms as form_view
from django.contrib.auth import *
from django.contrib.auth.forms import (
    AuthenticationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm,
)

#定义表单模型
class UserForm(form_view.Form):
    username = form_view.CharField(label='用户名：', max_length=100)
    password = form_view.CharField(label='密码：', widget=form_view.PasswordInput())

 
#登录
def Login(request):
    next = None
    if request.GET.get('next'):
        next = request.META['QUERY_STRING'].split('next=')[1].split("&type=qq")[0]
    if request.method == 'POST': 
         
        username = request.POST.get('username')
        password = request.POST.get('p') 
         
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                response = HttpResponseRedirect('/home')
                if next:
                    return redirect(next)
                    
                return response

        return render(request, 'user_login.html',{'message':'请填写正确的账号和密码!'})
    else: #get请求
        return render(request, 'user_login.html',{'message':''})

MyDjango/library/templates/library/add_book.html
{% extends "library/base.html" %}
{% load staticfiles %}
{% block title %}添加图书{% endblock %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
                {% if state == 'success' %}
                    <div class="well">
                        <h2 class="text-success text-center">添加成功</h2>
                    </div>
                {% endif %}
                <form method="POST" role="form" class="form-horizontal">
                    {% csrf_token %}
                    <h1 class="form-signin-heading text-center">添加图书</h1>

                    <div class="form-group">
                        <label for="id_name" class="col-md-3 control-label">书名：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" id="id_name" required name="name" autofocus>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_author" class="col-md-3 control-label">作者：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" required name="author" id="id_author">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_category" class="col-md-3 control-label">类型：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" required name="category" id="id_category">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_price" class="col-md-3 control-label">价格：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" required name="price" id="id_price">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_pubdate" class="col-md-3 control-label">出版日期：</label>
                        <div class="col-md-9">
                            <input type="date" class="form-control" required name="publish_date" id="id_pubdate">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-4 col-md-offset-4">
                            <button class="btn btn btn-primary btn-block" type="submit">提交</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

MyDjango/library/templates/library/add_img.html
{% extends "library/base.html" %}
{% block title %}添加图书{% endblock %}


<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
                {% if state == 'success' %}
                    <div class="well">
                        <h2 class="text-success text-center">添加成功</h2>
                    </div>
                {% elif state == 'error' %}
                    <div class="well">
                        <h2 class="text-danger text-center">添加失败</h2>
                    </div>
                {% endif %}
                <form method="POST" role="form" class="form-horizontal" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h1 class="form-signin-heading text-center">添加图片</h1>

                    <div class="form-group">
                        <label for="id_name" class="col-md-3 control-label">名称：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" id="id_name" required name="name" autofocus>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_description" class="col-md-3 control-label">描述：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" required name="description" id="id_description">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_book" class="col-md-3 control-label">所属书籍：</label>
                        <div class="col-md-9">
                            <select name="book" id="id_book" class="form-control">
                                {% for book in book_list %}
                                    <option value="{{ book.id }}">{{ book.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_img" class="col-md-3 control-label">图片：</label>
                        <div class="col-md-9">
                            <input type="file" id="id_img" name="img" class="form-control" required>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-4 col-md-offset-4">
                            <button class="btn btn btn-primary btn-block" type="submit">提交</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

MyDjango/library/templates/library/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!--[if lt IE 9]>
			<script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
</head>
<body>
<!--Here is the navbar-->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#navbar-collapse-basepage">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{% url 'homepage' %}" class="navbar-brand">Library</a>
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse-basepage">
            <ul class="nav navbar-nav">
                <li id="homepage"><a href="{% url 'homepage' %}">主页</a></li>
{#                {% if user and user.myuser.permission > 1 %}#}
                    <li id="add_book"><a href="{% url 'add_book' %}">添加图书</a></li>
                    <li id="add_img"><a href="{% url 'add_img' %}">添加图片</a></li>
{#                {% endif %}#}
                <li id="view_book"><a href="{% url 'view_book_list' %}">查看图书</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.username %}
                    <li><p class="navbar-text">欢迎你&nbsp;&nbsp;<span id="base_name">{{ user.username }}</span></p>
                    </li>
                    <li><a href="{% url 'logout' %}">注销</a></li>
                    <li><a href="{% url 'set_password' %}">修改密码</a></li>
                {% else %}
                    <li><a href="{% url 'signup' %}">注册</a></li>
                    <li><a href="{% url 'login' %}">登录</a></li>
                {% endif %}
            </ul>
        </div>

    </div>
</nav>
<!-- /nav -->
<!-- header -->
<header class="jumbotron subhead" id="header-base">
    <div class="container">
        <h1></h1>
        <h3>&emsp;&emsp;知识改变命运</h3>
    </div>
</header>
<!-- /.header -->
<!-- main part -->
{% block content %}{% endblock %}
<!-- /.main -->

<!-- footer -->
<footer class="footer" role="contentinfo">
    <hr>
    <div class="container">
        <p class="text-center"><strong>HIT-CS</strong></p>
        <p class="text-center">©All rights reserved</p>
        <h5 class="text-center"> Powered by&nbsp;<a href="http://zipinglv.pythonanywhere.com/">zipinglv</a></h5>
    </div>
</footer>
<!-- /.footer-->
<script type="text/javascript">
    $('#{{active_menu}}').addClass("active");
</script>
</body>
</html>

MyDjango/library/templates/library/detail.html
{% extends "library/base.html" %}
{% load staticfiles %}
{% block title %}查看图书{% endblock %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="col-md-5">
                    {% if book.image_set.all %}
                        <div id="carousel-generic" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                {% for img in book.img_set.all %}
                                    <li data-target="#carousel-generic" data-slide-to="{{ forloop.counter0 }}"
                                        {% if forloop.first %}class="active"{% endif %}></li>
                                {% endfor %}
                            </ol>
                            <div class="carousel-inner" role="listbox">
                                {% for img in book.image_set.all %}
                                    <div {% if forloop.first %}class="item active"{% else %}class="item"{% endif %}>
                                        <img class="img-rounded" src="{% url 'uploads' img.img %}">
                                    </div>
                                {% endfor %}
                            </div>
                            <a class="left carousel-control" href="#carousel-generic" role="button" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-generic" role="button" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                            </a>
                        </div>
                    {% else %}
                        <p class="text-center">暂无图片</p>
                    {% endif %}
                </div>
                <div class="col-md-6 col-md-offset-1">
                    <h2 class="text-center">{{ book.name }}</h2>
                    <br>
                    <h3>作者：{{ book.author }}</h3>
                    <h3>类别：{{ book.category }}</h3>
                    <h3>出版日期：{{ book.publish_date|date:"Y-m-d" }}</h3>
                    <h3>价格：{{ book.price|floatformat:2 }}</h3>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

MyDjango/library/templates/library/index.html
{% extends "library/base.html" %}
{% load staticfiles %}
{% block title %}book manager{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 well">
                <h2>&emsp;&emsp;Here is the homepage!</h2>
                <h3 class="text-center">Email:<span class="text-info">17701609050@163.com</span></h3>
            </div>
        </div>
    </div>

{% endblock %}

MyDjango/library/templates/library/login.html
{% extends "library/base.html" %}
{% load staticfiles %}
{% block title %}Register{% endblock %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
                {% if state == 'not_exist_or_password_error' %}
                    <div class="well">
                        <h2 class="text-danger text-center">用户不存在或密码错误</h2>
                    </div>
                {% endif %}
                <form method="POST" role="form" class="form-horizontal">
                    {% csrf_token %}
                    <h1 class="form-signin-heading text-center">请登陆</h1>

                    <div class="form-group">
                        <label for="id_user_name" class="col-md-3 control-label">用户名：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" id="id_user_name" required name="username"
                                   autofocus>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_password" class="col-md-3 control-label">密码：</label>
                        <div class="col-md-9">
                            <input type="password" class="form-control" required name="password" id="id_password">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-4 col-md-offset-4">
                            <button class="btn btn btn-primary btn-block" type="submit">登陆</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

MyDjango/library/templates/library/singup.html
{% extends "library/base.html" %}
{% load staticfiles %}
{% block title %}Register{% endblock %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
                {% if state == 'success' %}
                    <div class="well">
                        <h2 class="text-success text-center">注册成功！</h2>
                    </div>
                {% elif state == 'repeat_error' %}
                    <div class="well">
                        <h2 class="text-warning text-center">密码重复错误</h2>
                    </div>
                {% elif state == 'empty' %}
                    <div class="well">
                        <h2 class="text-warning text-center">密码不能为空</h2>
                    </div>
                {% elif state == 'user_exist' %}
                    <div class="well">
                        <h2 class="text-danger text-center">用户已经存在</h2>
                    </div>
                {% endif %}
                <form method="POST" role="form" class="form-horizontal">
                    {% csrf_token %}
                    <h1 class="form-signin-heading text-center">请注册</h1>

                    <div class="form-group">
                        <label for="id_user_name" class="col-md-3 control-label">用户名：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" id="id_user_name" required name="username"
                                   autofocus>
                            <span class="help-block">用于登陆，可以包括大小写字母和下划线。</span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_name" class="col-md-3 control-label">昵称：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" required name="nickname" id="id_name">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_passwd" class="col-md-3 control-label">密码：</label>
                        <div class="col-md-9">
                            <input type="password" class="form-control" required name="password" id="id_passwd">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_repasswd" class="col-md-3 control-label">重复密码：</label>
                        <div class="col-md-9">
                            <input type="password" class="form-control" required name="repeat_password"
                                   id="id_repasswd">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_email" class="col-md-3 control-label">电子邮件：</label>
                        <div class="col-md-9">
                            <input type="email" class="form-control" required name="email" id="id_email">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-4 col-md-offset-4">
                            <button class="btn btn btn-primary btn-block" type="submit" id="id_submit">注册</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>

{% endblock %}